### ISSUE TITLE
Layout Component isLandscape hook to children

### ISSUE THREAD

**Issue by jerrygzy** [theodorusclarence/ts-nextjs-tailwind-starter#101]
Hi Theodorus,

I am trying to pass a isLandscape hook to children, but got stuck. here is what I have wrote

```js
// Layout.tsx

import clsx from 'clsx';
import * as React from 'react';
import { useMediaQuery } from 'react-responsive';

import Footer from '@/components/layout/Footer';
import Header from '@/components/layout/Header';


const defaultLayout = {
  switch: false,
};

type LayoutProps = {
  templateTitle?: string;
  children: React.ReactNode;
} & Partial<typeof defaultLayout>;

export default function Layout(props: LayoutProps) {
  const m = {
    ...defaultLayout,
    ...props,
  };

const isLandscape = useMediaQuery({ query: '(orientation: landscape)' });

return (
       <div>
               <Header landscape={isLandscape}/>
               {m.children}
               <Footer landscape={isLandscape}/>
      </div>
  );
}
```

How can I pass the ```isLandscape``` hook to children?

**Comment by theodorusclarence** [comment]
Hey @jerrygzy, afaik, you can’t drill props to children. You need to create a React context to pass them

**Comment by jerrygzy** [comment]
thank you man, Saved my Day!
But one more thing,  should I do use useContext or zustand as a state manager? for this ```isLandscape``` example.

**Comment by theodorusclarence** [comment]
personally, I would call useMediaQuery on every component that I need.

But if you want to take the state manager path, because it is only one state, I would choose context if zustand has not been installed in the project.

But if you’re already using zustand, just go for it, far more readable and less boilerplate imo

**Comment by jerrygzy** [comment]
OK, will have a try with zustand, since I have used your extension pack 😁
