### ISSUE TITLE
Error yarn not recognize in husky

### ISSUE THREAD

**Issue by naufaldi** [theodorusclarence/ts-nextjs-tailwind-starter#11]
First time using husky, when use [Conventional Commit ](https://theodorusclarence.com/library/conventional-commit-readme) giving error something like this :
![image](https://user-images.githubusercontent.com/13159420/133015037-5d832180-2e60-40fd-a744-9b22f090ad46.png)

### Yarn Version
`1.22.11`

**Comment by theodorusclarence** [comment]
hi, it is updated in this commit https://github.com/theodorusclarence/ts-nextjs-tailwind-starter/commit/150aca43e502a6e7f57014bc7d22bdb4fc012a9d#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R47-R50

try changing `yarn eslint ...` to just `eslint`

**Comment by naufaldi** [comment]
its work. Thanks you @theodorusclarence
