### ISSUE TITLE
Include dark mode configuration

### ISSUE THREAD

**Issue by gleysonlf** [theodorusclarence/ts-nextjs-tailwind-starter#127]
I would first like to thank you for making this repository available, it helped me a lot and facilitated several environment configuration activities.

I would like to suggest setting dark mode in the application context, it would help a lot to use Tailwind resources in themes and components

- Below is an example of Next.js setting dark mode with useEffect:

![code](https://user-images.githubusercontent.com/33023194/166122886-daf530d4-4f1d-433f-8281-c548661686bd.png)

- An example of toogle button and output code:

![code2](https://user-images.githubusercontent.com/33023194/166123047-41e816b7-7198-4b34-9e4f-53057312737e.png)
![code3](https://user-images.githubusercontent.com/33023194/166123139-982a7240-b611-44d2-a887-b0bc36a1e7e2.png)
![rect952](https://user-images.githubusercontent.com/33023194/166123236-80cfaffe-fc12-4047-a5f6-50debb5bfbaa.png)

**_Once again, thank you for everything._**

**Comment by theodorusclarence** [comment]
Hi @gleysonlf, thanks for the suggestions and the awesome writeup 🔥. I would suggest using https://github.com/pacocoursey/next-themes for the dark mode functionality. 

Regarding the addition to the starter, I don't think I will add them for now. Adding dark mode might be beneficial if you often use dark mode when building a website. However, most of the time (at least for me and some of my colleagues) we don't need the dark mode and removing the configuration is much more of a hassle than adding it.

But you're allowed to fork the project and use your fork as a template instead 😃
