### ISSUE TITLE
standard-version is deprecated

### ISSUE THREAD

**Issue by LongJohnSilver1504** [theodorusclarence/ts-nextjs-tailwind-starter#140]
Hi!!!
Nice work here.
I'm just reviewing the dependencies and found this:
https://github.com/conventional-changelog/standard-version
`standard-version is deprecated. If you're a GitHub user, I recommend [release-please](https://github.com/googleapis/release-please) as an alternative. I encourage folks to fork this repository and, if a fork gets popular, I will link to it in this README.`
Maybe we could use the recommended library instead.
Thanks!!

**Comment by theodorusclarence** [comment]
Thanks for the heads up! I'll look into it later

**Comment by theodorusclarence** [comment]
Hey @LongJohnSilver1504 and others if you're reading this.

The github actions suggests to run it on every **push on main** 
https://github.com/google-github-actions/release-please-action#setting-up-this-action

Do you think this would be a great idea?
