### ISSUE TITLE
[Feature Request] Internationalization

### ISSUE THREAD

**Issue by bryantobing12** [theodorusclarence/ts-nextjs-tailwind-starter#149]
- Adding internalization be set up by default

**Comment by theodorusclarence** [comment]
Hi @bryantobing12, 

Nice suggestion! I think this would be more suitable on https://github.com/theodorusclarence/expansion-pack

If you would like to contribute, feel free to fork and open a PR, thanks!

**Comment by bryantobing12** [comment]
Hi @theodorusclarence. I agree. I created a pull request on https://github.com/theodorusclarence/expansion-pack

kindly check and review. Thanks!
