### ISSUE TITLE
favicon.ico not found

### ISSUE THREAD

**Issue by cha2hyun** [theodorusclarence/ts-nextjs-tailwind-starter#160]
console says GET http://localhost:3000/favicon.ico 404 (Not Found)
(i didn't edit anythings in src > components > Seo.tsx or public > favicon)
![image](https://user-images.githubusercontent.com/56015532/184056114-d88d4cf1-7abf-4484-b66e-2358806f8758.png)

The problem is when i Link to other pages, console says it visiting 404 pages several times.

404.tsx
```typescript
import * as React from 'react';
import { RiAlarmWarningFill } from 'react-icons/ri';

import Layout from '@/components/layout/Layout';
import ArrowLink from '@/components/links/ArrowLink';
import Seo from '@/components/Seo';

export default function NotFoundPage() {
  return (
    <Layout title='404'>
      <Seo templateTitle='Not Found' />
...
```

Layout.tsx
```typescript
import * as React from 'react';

import Header from './Header';

export default function Layout({
  children,
  title,
  prevUrl,
}: {
  children: React.ReactNode;
  title: string;
  prevUrl?: string;
}) {
  return (
    <>
      <Header title={title} prevUrl={prevUrl} />
      <section className='min-h-full'>{children}</section>
...

```
Header.tsx
```typescript
export default function Header({
  title,
  prevUrl,
}: {
  title: string;
  prevUrl?: string;
}) {
console.log(title, prevUrl)
...
```

When i navigate to other pages console says like below.
<img width="462" alt="image" src="https://user-images.githubusercontent.com/56015532/184057292-f20da421-1092-4c97-a641-f27197bf9112.png">

**Comment by theodorusclarence** [comment]
Looks like we need to move the favicon to the root public. I'll fix it later

**Comment by cha2hyun** [comment]
> Looks like we need to move the favicon to the root public. I'll fix it later

👍
