### ISSUE TITLE
support question: Commiting to Git takes a really long time

### ISSUE THREAD

**Issue by osseonews** [theodorusclarence/ts-nextjs-tailwind-starter#169]
Whenever we commit to GIT locally using this repo, the commit takes a really, really long time, say 2 minutes. I believe this has something to do with husky, but I'm not sure, as I don't understand husky at all or what other pre-commit checks are done here.  Removing husky from the package.json didn't seem to help either. Anyway, any idea what we can do to speed up the commits?

**Comment by theodorusclarence** [comment]
Hi, I've never experienced this, have you also tried removing the .husky folder?

Also, how large are your codebase? If it is really large, then it is a normal behaviour because husky will check prettier and eslint before every commit.

**Comment by osseonews** [comment]
Yes, when I remove the .husky folder it is much faster. Codebase is not too large.  However, I have had issues with husky before. Really slows things down, in my experience, though it is very helpful.

**Comment by theodorusclarence** [comment]
Hi, I couldn't replicate this tbh. Feel free to remove the husky if you have trouble with it. Thanks!
