### ISSUE TITLE
Generic AppProps

### ISSUE THREAD

**Issue by quinn-eschenbach** [theodorusclarence/ts-nextjs-tailwind-starter#177]
Hi, thanks for the awesome template

I just encountered [this](https://stackoverflow.com/questions/64722812/what-typescript-type-should-nextjs-app-tsx-component-and-pageprops-be) little update to the AppProps in the _app.tsx file

Basically AppProps is now generic and you can pass your custom props to it

Like here when using next-auth 

```
import { Session } from 'next-auth/core/types';
import { SessionProvider } from 'next-auth/react';
interface CustomPageProps {
  session: Session;
}
function MyApp({ Component, pageProps }: AppProps<CustomPageProps>) {
  return (
      <SessionProvider session={pageProps.session} refetchInterval={0}>
        <Component {...pageProps} />
      </SessionProvider>
  );
}
```

I thought you might want to include it

Cheers

**Comment by theodorusclarence** [comment]
Hey, looks good. I’ll include it with the next 13 update

**Comment by theodorusclarence** [comment]
I just realized that there are no CustomPageProps needed in the base starter 😃. So I don't think it is needed to add it for now.

Thanks for your information! This will come in handy with next-auth usage.
