### ISSUE TITLE
setting theme to white by default

### ISSUE THREAD

**Issue by Codigo-Fuentes** [theodorusclarence/ts-nextjs-tailwind-starter#208]
https://github.com/theodorusclarence/ts-nextjs-tailwind-starter/blob/10d639b39b9767727f2248a9dd3c38aeaf966133/src/components/Seo.tsx#L89

this line `<meta name='theme-color' content='#ffffff' />` is setting the theme to white which causes status bar and behind page bg on iPhone to be white which was hard to debug I suggest removing it or adding a comment.

**Comment by theodorusclarence** [comment]
Hi thanks for the report, if it is removed, will the default value cause a problem?

**Comment by theodorusclarence** [comment]
Hi, @Codigo-Fuentes 

Any update on my question?
