### ISSUE TITLE
Resize Cursor on Link & Button

### ISSUE THREAD

**Issue by VIEWVIEWVIEW** [theodorusclarence/ts-nextjs-tailwind-starter#21]
Just wanted to let you know that the cursor on https://tsnext-tw.thcl.dev/components changes to the resize cursor, instead of pointer when hovering above a Link or Button component.
![Link](https://i.imgur.com/NZf6Dwe.png)
![Button](https://i.imgur.com/4Cfs9Sx.png)

https://github.com/theodorusclarence/ts-nextjs-tailwind-starter/blob/5c06f90285e4b1bf10e60a1508af5465d22d2fac/src/components/links/UnstyledLink.tsx#L40

This confused me a little bit when checking out the demo, since the resize cursor indicated that you could resize the element. I would change this behaviour.

**Comment by theodorusclarence** [comment]
Thanks for your feedback, on Mac it was supposed to mimic 'opening in new tab'. It looks better on mac honestly, and I just realized it didn't really work with other OS. 

![image](https://user-images.githubusercontent.com/55318172/137332290-1b33bf75-0474-4451-bc7d-86a71f473e4b.png)

I'll try to fix it with a custom cursor.
