### ISSUE TITLE
issue changing site title

### ISSUE THREAD

**Issue by jcstein** [theodorusclarence/ts-nextjs-tailwind-starter#219]
I'm attempting to change the title of an instance of this site, but not having luck when [changing the default values in `Seo.tsx`](https://github.com/jcstein/node-rpc-docs/blob/5c8a21deb95649a85a91ba2854208ee5fcc95909/src/components/Seo.tsx#L6)

Could you please help guide me in the right direction? I think I must have missed a step somewhere. Thanks!

**Comment by jcstein** [comment]
added you to the repo 😄

**Comment by theodorusclarence** [comment]
You didn't add the Seo component to your [pages/index.tsx](https://github.com/jcstein/node-rpc-docs/blob/5c8a21deb95649a85a91ba2854208ee5fcc95909/src/pages/index.tsx#L86) page

It should be called like the example page
https://github.com/theodorusclarence/ts-nextjs-tailwind-starter/blob/cd315f7751a008ef15e848714e47c8f97c7e00dc/src/pages/index.tsx#L27
