### ISSUE TITLE
Local fonts are not loading when deoploying

### ISSUE THREAD

**Issue by solkpolk** [theodorusclarence/ts-nextjs-tailwind-starter#236]
Works perfectly locally but when pushing to vercel the custom fonts are not being used

**Comment by theodorusclarence** [comment]
Are you using the default inter, or are you using your own custom font?

**Comment by Johnrobmiller** [comment]
I think this is probably because `font-display` is set to optional. Set it to `block` and maybe it works

**Comment by nslee333** [comment]
> I think this is probably because `font-display` is set to optional. Set it to `block` and maybe it works

This worked for me 👍🏼
