### ISSUE TITLE
What happened to the SEO component?

### ISSUE THREAD

**Issue by Ivan-Tigan** [theodorusclarence/ts-nextjs-tailwind-starter#243]
Hi, I understand that there was some migration to new a standard with changes from pages to app, etc.

There used to be an Seo component. What happened to it? Is it no longer appropriate for the new standard? Can I just use it as it used to be or would it no longer work?

What I am talking about:  
 https://github.com/theodorusclarence/ts-nextjs-tailwind-starter/blob/pages-directory/src/components/Seo.tsx

**Comment by theodorusclarence** [comment]
Hi,

Yeah, it bums me out too. But it no longer works with the app directory. Next.js only supports metadata using a const like [this](https://nextjs.org/docs/app/building-your-application/optimizing/metadata). It's one thing that I don't like for the new app directory
