### ISSUE TITLE
font-display should not be `optional` by default

### ISSUE THREAD

**Issue by Johnrobmiller** [theodorusclarence/ts-nextjs-tailwind-starter#246]
I think it's very questionable to default to optionally displaying the fonts by setting `font-display` to `optional` in the `@font-face` in `globals.css`. I know that only `Inter` is set to `optional`, but devs often copy/paste the whole `@font-face` that's in the template when importing their own fonts, trusting it will work for them, and the `font-display` property comes along with it. 

You really would be required to give zero fucks about the design of your app/site to be ok with not loading your fonts to save the tiny sliver of time it takes to load them. Also, if you are working with a designer, setting the fonts to `optional` is just downright disrepectful, it's like you are saying "I know you problably carefully picked out these fonts for this design, but I don't care and I'm going to optionally load them anyways."

The default for the `font-display` value should not be `optional`. Maybe `block`? Or, maybe keep it s `optional` but add a helpful comment?

**Comment by theodorusclarence** [comment]
Hi, that's a great idea. 

Feel free to open up a PR, thanks!
