### ISSUE TITLE
i18n not setting html lang in next.config.js

### ISSUE THREAD

**Issue by nslee333** [theodorusclarence/ts-nextjs-tailwind-starter#278]
Love your starter by the way, thanks for setting it up. 😃 

Currently having an issue with i18n not setting the html lang element, not sure if it is an issue with the starter or if I'm missing something. 

`next.config.js`
``` 
const nextConfig = {
  eslint: {
    dirs: ['src'],
  },
  reactStrictMode: true,
  swcMinify: true,

  i18n: {
    locales: ['en-US'],
    defaultLocale: 'en-US',
  },

...
```

**Comment by theodorusclarence** [comment]
Hi, I never used built-in i18n before. However in this starter we declare html here. So you might need to do some custom config to get the current lang

https://github.com/theodorusclarence/ts-nextjs-tailwind-starter/blob/main/src/app/layout.tsx

**Comment by nslee333** [comment]
I was trying to use i18n since I thought that it was the only option to set the html lang attribute, which now I know better - I just set it manually so that works. Thanks for the help.
