### ISSUE TITLE
Format document is not working

### ISSUE THREAD

**Issue by ansh-les** [theodorusclarence/ts-nextjs-tailwind-starter#290]
<img width="329" alt="image" src="https://github.com/user-attachments/assets/62e2d4c6-1423-4bcf-a7df-a4b0007cbc08">

The plugin now does not support `prettier@2.0.0` which is what gets installed.
https://github.com/tailwindlabs/prettier-plugin-tailwindcss/?tab=readme-ov-file#upgrading-to-v05x

**Comment by theodorusclarence** [comment]
Will check this around the weekend!

**Comment by theodorusclarence** [comment]
After some checking, I don't think I can replicate this
