### ISSUE TITLE
Update pnpm action setup

### ISSUE THREAD

**Issue by Migueacalle98** [theodorusclarence/ts-nextjs-tailwind-starter#302]
When installing `pnpm` v9 on local github the action for lint fails when installing dependencies to a lock file of an incompatible version.

I was able to fix this by updating pnpm/action-setup@v2 -> pnpm/action-setup@v4, and marking version as 9.

More details about v2 being deprecated at [https://github.com/marketplace/actions/setup-pnpm](https://github.com/marketplace/actions/setup-pnpm)

**Comment by theodorusclarence** [comment]
Cool! Do you want to open a PR or should I? @Migueacalle98

**Comment by Migueacalle98** [comment]
@theodorusclarence Thank you very much for taking care of this! I was caught up at the time you wrote!
