### ISSUE TITLE
Problem while running npm install

### ISSUE THREAD

**Issue by camilo-mujica** [theodorusclarence/ts-nextjs-tailwind-starter#85]
Hello! First of all, thank you very mucho for this awesome starter!
I keep getting this problem while running npm install,
What coul it be?

![image](https://user-images.githubusercontent.com/84539709/149629005-7e182a19-b25a-42ba-83ec-cb476f41df7b.png)

**Comment by theodorusclarence** [comment]
Hey, I think there is a dependency version error on this starter. I’ll try to fix it tomorrow.

If you need it done quickly, I believe using yarn will fix itself. Looks like npm won’t resolve the peer deps error automatically

or you can downgrade the `eslint-plugin-unused-import` to v1.x.x

**Comment by camilo-mujica** [comment]
I don't need it fast, on the contrary, thank you very much for responding so quickly! This starter is great man!

BTW your website is awesome :)

**Comment by theodorusclarence** [comment]
> This starter is great man! BTW your website is awesome :)

Thanks!

I downgraded the package, but I'll still suggest using yarn instead, because all development features such as:
- husky post-merge
- github actions lint

are all designated and cached for yarn usage.
