### ISSUE TITLE
Getting errors in tsconfig.json file

### ISSUE THREAD

**Issue by Kingkon963** [theodorusclarence/ts-nextjs-tailwind-starter#93]
I'm getting this error whenever I try to add Tailwindcss to my Nextjs project initiated with "create-next-app --typescript". 
Therefore I wanted to try your template but now having the exact same issue. 

![image](https://user-images.githubusercontent.com/33956213/151255455-72fc2ad4-8c98-4fb0-bc38-6961d38fc113.png)

I have tried installing types for 'accepts' using "yarn add @types/accepts" but then it shows the same error for "body-parser" and keeps going on and on and telling me to add types for different packages which are unknown to me.

Do you know why is this happening?

**Comment by Kingkon963** [comment]
This issue got resolved after installing all of the following types. But I still couldn't figure out why that happened

```
@types/accepts
@types/body-parser
@types/bson
@types/content-disposition
@types/cookies
@types/formidable
@types/fs-capacitor
@types/glob
@types/hoist-non-react-statics
@types/http-assert
@types/http-errors
@types/invariant
@types/json-schema
@types/koa
@types/koa-bodyparser
@types/koa__cors
@types/lodash
@types/long
@types/mongodb
@types/node-fetch
@types/react-redux
@types/ws
```

**Comment by theodorusclarence** [comment]
I never get this error before, can you try with this exact command? without the `--typescript` flag

```npx create-next-app -e https://github.com/theodorusclarence/ts-nextjs-tailwind-starter project-name```

**Comment by theodorusclarence** [comment]
is there any update? @Kingkon963

**Comment by Kingkon963** [comment]
Hi @theodorusclarence,
Sorry for being late and thank you for your reply.



> I never get this error before, can you try with this exact command? without the `--typescript` flag
> 
> `npx create-next-app -e https://github.com/theodorusclarence/ts-nextjs-tailwind-starter project-name`

I have just tried this and the error is still there. I neither faced this error before the release of Tailwindcss v3

**Comment by Kingkon963** [comment]
I got rid of this annoying error after doing the following,

1. Installed _@types/node_ `yarn add -D @types/node`
2. Added `"types": ["node"]` in the _compilerOptions_ of the **tsconfig.json** file

![Screenshot 2022-09-09 215114](https://user-images.githubusercontent.com/33956213/189390860-146dfac7-6615-4572-96d0-fa0f8823900e.jpg)
