### ISSUE TITLE
NextImage component not working properly

### ISSUE THREAD

**Issue by mukhlisakbr** [theodorusclarence/ts-nextjs-tailwind-starter#97]
I think the `NextImage` component not properly optimizing images because `next/image` has been set to `layout='responsive'`. If I look in the `components.tsx` page there is a usage example, but when the image is loaded it is not actually optimized 

produced image URL: https://tsnext-tw.thcl.dev/_next/image?url=%2Ffavicon%2Fapple-icon-180x180.png&w=1920&q=75

it should be `w=180`  but because `layout='responsive'` it uses screen width/parent container size as image width which is `w=1920` in my case. I think just leaving it as default layout or removing the layout prop and fixed image size will be working fine

**Comment by theodorusclarence** [comment]
I see, so the responsive is best optimized for full bleed images?

Without the layout responsive, how about for smaller screen like 320 width (iphone)? Will it optimize them?
